<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Core.WorkflowEngine.Persistence\Core.WorkflowEngine.Persistence.csproj" />
    <ProjectReference Include="..\Core.WorkflowEngine.Application\Core.WorkflowEngine.Application.csproj" />
  </ItemGroup>

</Project>
