services:   
  # İlk Olarak Veritabanları Ayağa Kaldırılır.
  core_workflowEngine_db:
    image: postgres:16
    container_name: Core_WorkflowEngine_Db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456Aa*
      POSTGRES_DB: HealthCare_WorkflowEngine_Db
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=tr-TR --encoding=UTF8"
    ports:
      - "5438:5432"
    volumes:
      - workflowEngine_db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - HealthCare_Network
  
  core_identityserver_db:
    image: postgres:16
    container_name: Core_IdentityServer_Db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456Aa*
      POSTGRES_DB: HealthCare_IdentityServer_Db
    ports:
      - "5434:5432"
    volumes:
      - identity_db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - HealthCare_Network
    
  healthcare_descriptions_db:
    image: postgres:16
    container_name: HealthCare_Descriptions_Db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456Aa*
      POSTGRES_DB: healthcare_descriptions_db
    ports:
      - "5435:5432"
    volumes:
      - descriptions_db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - HealthCare_Network
    
  healthcare_operations_db:
    image: postgres:16
    container_name: HealthCare_Operations_Db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456Aa*
      POSTGRES_DB: HealthCare_Operations_Db
    ports:
      - "5436:5432"
    volumes:
      - operations_db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - HealthCare_Network

volumes:
  workflowEngine_db_data:
  identity_db_data:
  descriptions_db_data:
  operations_db_data:
  
networks:
  HealthCare_Network:
    external: true